version: '3.7'
services:
  ny-taxi-database:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - "./ny_taxi_pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    networks:
      - pg-network

  pgadmin-server:
    image: dpage/pgadmin4:latest
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    networks:
      - pg-network

networks:
  # The presence of these objects is sufficient to define them
  pg-network: {}